name = "hooksocket"
main = "worker.js"
compatibility_date = "2025-06-28"

durable_objects.bindings = [
  { name = "WSROOM", class_name = "WebSocketRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketRoom"]
